---
apiVersion: v1
kind: Namespace
metadata:
  name: qrcode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qrcode
  name: deployment-qrcode
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-qrcode
  replicas: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-qrcode
    spec:
      containers:
      - image: 922823096026.dkr.ecr.us-east-1.amazonaws.com/avengers:ms2v1
        imagePullPolicy: Always
        name: app-qrcode
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: qrcode
  name: service-qrcode
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-qrcode
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: qrcode
  name: ingress-qrcode
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-qrcode
              servicePort: 80
